package anypath

//go:generate ragel -Z -G2 parsePath.rl -o parsePath.go
//go:generate bash -c "sed -i '4,4 s|^|/*\\n|' parsePath.go"
//go:generate bash -c "sed -i '5,5 s|^|┌───────────────────────────────────────────────────────────┐\\n|' parsePath.go"
//go:generate bash -c "sed -i '6,6 s|^|│                                                           │\\n|' parsePath.go"
//go:generate bash -c "sed -i '7,7 s|^|│ Do not edit! The file was autogenerated from parsePath.rl │\\n|' parsePath.go"
//go:generate bash -c "sed -i '8,8 s|^|│ by command: ragel -Z -G2 parsePath.rl -o parsePath.go     │\\n|' parsePath.go"
//go:generate bash -c "sed -i '9,9 s|^|│                                                           │\\n|' parsePath.go"
//go:generate bash -c "sed -i '10,10 s|^|└───────────────────────────────────────────────────────────┘\\n|' parsePath.go"
//go:generate bash -c "sed -i '11,11 s|^|*/\\n|' parsePath.go"
